version: "3"
services:
    ngnix:
        ports: 
            - "3000:80"
        volumes: 
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    node-app:
        build:
            context: .
            args:
                NODE_ENV: dev
        volumes:
            - ./:/app
#            - /app/node_modules
        environment: 
            - NODE_ENV=development
            - MONGO_USER=sarath
            - MONGO_PASS=pass
            - SESSION_SECRET=secret
        command: npm run dev
    mongo:
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=sarath
            - MONGO_INITDB_ROOT_PASSWORD=pass      