version: "3"
services: 
    ngnix:
        image: nginx:stable-alpine
    node-app:
        build: .
        environment: 
            - PORT=3000
        depends_on: 
            - mongo    
    
    mongo:
        image: mongo
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=sarath
            - MONGO_INITDB_ROOT_PASSWORD=pass
        volumes: 
            - mongo-db:/data/db

    redis:
        image: redis        

volumes: 
    mongo-db: